export const DEFAULT_EXPENSE_TYPES = [
  "Salary",
  "Utilities",
  "Maintenance",
  "Groceries",
  "Cleaning Supplies",
  "Furniture",
  "Internet & Cable",
  "Security",
  "Transport",
  "Medical",
  "Miscellaneous",
];

export interface Expense {
  id: string;
  type: string;
  description: string;
  amount: number;
  date: string;
  paidTo: string;
  reference: string; // optional ref like salary payment id
  autoGenerated: boolean; // true if created from salary payment
  createdAt: string;
}

const TYPES_KEY = "hostel_expense_types";
const EXPENSES_KEY = "hostel_expenses";

// Expense Types
export function getExpenseTypes(): string[] {
  const data = localStorage.getItem(TYPES_KEY);
  if (!data) return DEFAULT_EXPENSE_TYPES;
  const parsed = JSON.parse(data) as string[];
  return parsed.length > 0 ? parsed : DEFAULT_EXPENSE_TYPES;
}

export function saveExpenseTypes(types: string[]) {
  localStorage.setItem(TYPES_KEY, JSON.stringify(types));
}

export function addExpenseType(type: string) {
  const types = getExpenseTypes();
  if (!types.includes(type)) {
    types.push(type);
    saveExpenseTypes(types);
  }
}

export function removeExpenseType(type: string) {
  const types = getExpenseTypes().filter((t) => t !== type);
  saveExpenseTypes(types);
}

export function updateExpenseType(oldType: string, newType: string) {
  const types = getExpenseTypes().map((t) => (t === oldType ? newType : t));
  saveExpenseTypes(types);
}

// Expenses
export function getExpenses(): Expense[] {
  const data = localStorage.getItem(EXPENSES_KEY);
  return data ? JSON.parse(data) : [];
}

export function saveExpense(expense: Expense) {
  const expenses = getExpenses();
  expenses.push(expense);
  localStorage.setItem(EXPENSES_KEY, JSON.stringify(expenses));
}

export function updateExpense(updated: Expense) {
  const expenses = getExpenses().map((e) => (e.id === updated.id ? updated : e));
  localStorage.setItem(EXPENSES_KEY, JSON.stringify(expenses));
}

export function deleteExpense(id: string) {
  const expenses = getExpenses().filter((e) => e.id !== id);
  localStorage.setItem(EXPENSES_KEY, JSON.stringify(expenses));
}

// Auto-create expense from salary payment
export function createSalaryExpense(employeeName: string, amount: number, paymentId: string, payType: string) {
  const expense: Expense = {
    id: crypto.randomUUID(),
    type: "Salary",
    description: `${payType.charAt(0).toUpperCase() + payType.slice(1)} payment to ${employeeName}`,
    amount,
    date: new Date().toISOString().split("T")[0],
    paidTo: employeeName,
    reference: paymentId,
    autoGenerated: true,
    createdAt: new Date().toISOString(),
  };
  saveExpense(expense);
}
