import { Employee, getEmployees } from "./employeeStore";

const SEED_KEY = "hostel_employees_seeded_v1";

export function seedEmployees() {
  if (localStorage.getItem(SEED_KEY)) return;

  const existing = getEmployees();
  if (existing.length === 0) {
    const employees: Employee[] = [
      {
        id: "emp-1",
        fullName: "Rahim Bakhsh",
        fatherName: "Abdul Bakhsh",
        cnic: "35301-1111111-1",
        phone: "0300-1112233",
        email: "rahim.b@email.com",
        dateOfBirth: "1985-03-10",
        gender: "Male",
        address: "Village Kot Addu",
        city: "Muzaffargarh",
        state: "Punjab",
        country: "Pakistan",
        emergencyName: "Abdul Bakhsh",
        emergencyRelation: "Father",
        emergencyPhone: "0301-4445566",
        emergencyAltPhone: "",
        guardianName: "Abdul Bakhsh",
        guardianCnic: "35301-2222222-1",
        guardianPhone: "0301-4445566",
        guardianAddress: "Village Kot Addu, Muzaffargarh",
        bloodGroup: "O+",
        medicalConditions: "None",
        allergies: "None",
        selfImage: "",
        idCardFront: "",
        idCardBack: "",
        policeCharacterCert: "",
        dutyType: "Cook",
        salary: 25000,
        totalLeaves: 2,
        leavesTaken: 0,
        joiningDate: "2025-06-01",
        residesInHostel: true,
        assignedRoom: "Staff Room 1",
        assignedBed: "Bed A",
        hostelMess: true,
        messCharges: 0,
        status: "active",
        createdAt: "2025-06-01T10:00:00Z",
      },
      {
        id: "emp-2",
        fullName: "Naseem Aslam",
        fatherName: "Muhammad Aslam",
        cnic: "35302-3333333-3",
        phone: "0312-7778899",
        email: "naseem.a@email.com",
        dateOfBirth: "1990-07-22",
        gender: "Male",
        address: "House 5, Street 2, Satellite Town",
        city: "Rawalpindi",
        state: "Punjab",
        country: "Pakistan",
        emergencyName: "Muhammad Aslam",
        emergencyRelation: "Father",
        emergencyPhone: "0312-1112233",
        emergencyAltPhone: "",
        guardianName: "Muhammad Aslam",
        guardianCnic: "35302-4444444-1",
        guardianPhone: "0312-1112233",
        guardianAddress: "House 5, Satellite Town, Rawalpindi",
        bloodGroup: "A+",
        medicalConditions: "None",
        allergies: "None",
        selfImage: "",
        idCardFront: "",
        idCardBack: "",
        policeCharacterCert: "",
        dutyType: "Security Guard",
        salary: 20000,
        totalLeaves: 2,
        leavesTaken: 1,
        joiningDate: "2025-08-15",
        residesInHostel: true,
        assignedRoom: "Staff Room 2",
        assignedBed: "Bed A",
        hostelMess: true,
        messCharges: 0,
        status: "active",
        createdAt: "2025-08-15T10:00:00Z",
      },
      {
        id: "emp-3",
        fullName: "Shamim Bibi",
        fatherName: "Ghulam Hussain",
        cnic: "35303-5555555-5",
        phone: "0345-9990011",
        email: "",
        dateOfBirth: "1988-11-05",
        gender: "Female",
        address: "House 12, G-9/1",
        city: "Islamabad",
        state: "ICT",
        country: "Pakistan",
        emergencyName: "Ghulam Hussain",
        emergencyRelation: "Father",
        emergencyPhone: "0345-2223344",
        emergencyAltPhone: "",
        guardianName: "Ghulam Hussain",
        guardianCnic: "35303-6666666-1",
        guardianPhone: "0345-2223344",
        guardianAddress: "House 12, G-9/1, Islamabad",
        bloodGroup: "B+",
        medicalConditions: "None",
        allergies: "None",
        selfImage: "",
        idCardFront: "",
        idCardBack: "",
        policeCharacterCert: "",
        dutyType: "Cleaner",
        salary: 18000,
        totalLeaves: 2,
        leavesTaken: 0,
        joiningDate: "2025-09-01",
        residesInHostel: false,
        assignedRoom: "",
        assignedBed: "",
        hostelMess: false,
        messCharges: 0,
        status: "active",
        createdAt: "2025-09-01T10:00:00Z",
      },
      {
        id: "emp-4",
        fullName: "Tariq Mehmood",
        fatherName: "Mehmood Khan",
        cnic: "35304-7777777-7",
        phone: "0333-5556677",
        email: "tariq.m@email.com",
        dateOfBirth: "1992-01-18",
        gender: "Male",
        address: "Flat 3, F-10 Markaz",
        city: "Islamabad",
        state: "ICT",
        country: "Pakistan",
        emergencyName: "Mehmood Khan",
        emergencyRelation: "Father",
        emergencyPhone: "0333-1119988",
        emergencyAltPhone: "0300-7776655",
        guardianName: "Mehmood Khan",
        guardianCnic: "35304-8888888-1",
        guardianPhone: "0333-1119988",
        guardianAddress: "Flat 3, F-10 Markaz, Islamabad",
        bloodGroup: "AB-",
        medicalConditions: "None",
        allergies: "None",
        selfImage: "",
        idCardFront: "",
        idCardBack: "",
        policeCharacterCert: "",
        dutyType: "Manager",
        salary: 40000,
        totalLeaves: 4,
        leavesTaken: 2,
        joiningDate: "2025-05-01",
        residesInHostel: false,
        assignedRoom: "",
        assignedBed: "",
        hostelMess: false,
        messCharges: 0,
        status: "active",
        createdAt: "2025-05-01T10:00:00Z",
      },
      {
        id: "emp-5",
        fullName: "Akbar Ali",
        fatherName: "Nawaz Ali",
        cnic: "35305-9999999-9",
        phone: "0321-3334455",
        email: "",
        dateOfBirth: "1995-04-30",
        gender: "Male",
        address: "Village Gujar Khan",
        city: "Rawalpindi",
        state: "Punjab",
        country: "Pakistan",
        emergencyName: "Nawaz Ali",
        emergencyRelation: "Father",
        emergencyPhone: "0321-6667788",
        emergencyAltPhone: "",
        guardianName: "Nawaz Ali",
        guardianCnic: "35305-0000000-1",
        guardianPhone: "0321-6667788",
        guardianAddress: "Village Gujar Khan, Rawalpindi",
        bloodGroup: "O-",
        medicalConditions: "Lower back pain",
        allergies: "None",
        selfImage: "",
        idCardFront: "",
        idCardBack: "",
        policeCharacterCert: "",
        dutyType: "Cook Helper",
        salary: 15000,
        totalLeaves: 2,
        leavesTaken: 2,
        joiningDate: "2025-10-01",
        residesInHostel: true,
        assignedRoom: "Staff Room 1",
        assignedBed: "Bed B",
        hostelMess: true,
        messCharges: 0,
        status: "active",
        createdAt: "2025-10-01T10:00:00Z",
      },
    ];
    localStorage.setItem("hostel_employees", JSON.stringify(employees));
  }

  localStorage.setItem(SEED_KEY, "true");
}
