import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { apiGet, apiPost, apiPut, apiDelete } from "@/lib/api";

export interface ExpenseType {
  id: string;
  name: string;
  scope?: "global" | "branch";
  officeId?: string | null;
  office?: { id: string; name: string; city: string } | null;
  createdAt: string;
}

export type ExpenseTypeInput = {
  name: string;
  scope?: "global" | "branch";
  officeId?: string;
};

export interface Expense {
  id: string;
  officeId?: string;
  type: string;
  description?: string;
  amount: number;
  date: string;
  paidTo?: string;
  reference?: string;
  autoGenerated: boolean;
  createdAt: string;
}

export type ExpenseInput = {
  officeId?: string;
  type: string;
  description?: string;
  amount: number;
  date: string;
  paidTo?: string;
};

const KEY = ["expenses"] as const;
const TYPES_KEY = ["expenseTypes"] as const;

// ── Expense Types ─────────────────────────────────────────────────────────────

export function useExpenseTypes() {
  return useQuery({ queryKey: TYPES_KEY, queryFn: () => apiGet<ExpenseType[]>("/expenses/types"), staleTime: 10 * 60 * 1000 });
}

export function useCreateExpenseType() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (data: ExpenseTypeInput) => apiPost<ExpenseType>("/expenses/types", data),
    onSuccess: () => qc.invalidateQueries({ queryKey: TYPES_KEY }),
  });
}

export function useDeleteExpenseType() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (id: string) => apiDelete(`/expenses/types/${id}`),
    onSuccess: () => qc.invalidateQueries({ queryKey: TYPES_KEY }),
  });
}

// ── Expenses ──────────────────────────────────────────────────────────────────

export function useExpenses(filters?: { officeId?: string; type?: string; month?: string }) {
  const params = new URLSearchParams();
  if (filters?.officeId && filters.officeId !== "all") params.set("officeId", filters.officeId);
  if (filters?.type && filters.type !== "all") params.set("type", filters.type);
  if (filters?.month) params.set("month", filters.month);
  const qs = params.toString();
  return useQuery({
    queryKey: [...KEY, filters],
    queryFn: () => apiGet<Expense[]>(`/expenses${qs ? `?${qs}` : ""}`),
    staleTime: 2 * 60 * 1000,
  });
}

export function useAllExpenses(filters?: { officeId?: string; month?: string }) {
  const params = new URLSearchParams();
  if (filters?.officeId && filters.officeId !== "all") params.set("officeId", filters.officeId);
  if (filters?.month) params.set("month", filters.month);
  const qs = params.toString();
  return useQuery({
    queryKey: [...KEY, "all", filters],
    queryFn: () => apiGet<Expense[]>(`/expenses/all${qs ? `?${qs}` : ""}`),
    staleTime: 2 * 60 * 1000,
  });
}

export function useCreateExpense() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (data: ExpenseInput) => apiPost<Expense>("/expenses", data),
    onSuccess: () => qc.invalidateQueries({ queryKey: KEY }),
  });
}

export function useUpdateExpense() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: ({ id, ...data }: Partial<ExpenseInput> & { id: string }) => apiPut<Expense>(`/expenses/${id}`, data),
    onSuccess: () => qc.invalidateQueries({ queryKey: KEY }),
  });
}

export function useDeleteExpense() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (id: string) => apiDelete(`/expenses/${id}`),
    onSuccess: () => qc.invalidateQueries({ queryKey: KEY }),
  });
}
